spring:
  config:
    activate:
      on-profile: test
subway:
  app:
    github:
      client_id: 'client_id'
      client_secret: 'client_secret'
      access_token_uri: http://localhost:8080/github/login/oauth/access_token
      user_info_uri: http://localhost:8080/github/user
    user_service:
      create_url: http://localhost:8080/members
      me_url: http://localhost:8080/members
    auth-service:
      token-url: http://localhost:8080/login/oauth/access_token
---
spring:
  config:
    activate:
      on-profile: prod
subway:
  app:
    github:
      client_id: 'client_id'
      client_secret: 'client_secret'
      access_token_uri: http://subway.nextstep.com/github/login/oauth/access_token
      user_info_uri: http://subway.nextstep.com/github/user
