SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE STATION RESTART IDENTITY;
TRUNCATE TABLE LINE RESTART IDENTITY;
TRUNCATE TABLE SECTION RESTART IDENTITY;
TRUNCATE TABLE FAVORITE RESTART IDENTITY;
TRUNCATE TABLE Member RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;