export const SET_STATIONS = 'setStations'
export const SHOW_SNACKBAR = 'showSnackbar'
export const HIDE_SNACKBAR = 'hideSnackbar'
export const SET_LINES = 'setLines'
export const SET_LINE = 'setLine'
