ALTER TABLE STATION ALTER COLUMN id RESTART WITH 1;
ALTER TABLE LINE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE EDGE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE USER ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FAVORITE ALTER COLUMN id RESTART WITH 1;
