SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE station;
TRUNCATE TABLE line;
TRUNCATE TABLE section;
TRUNCATE TABLE favorite;
TRUNCATE TABLE member;

ALTER TABLE station ALTER COLUMN id RESTART WITH 1;
ALTER TABLE line ALTER COLUMN id RESTART WITH 1;
ALTER TABLE section ALTER COLUMN id RESTART WITH 1;
ALTER TABLE favorite ALTER COLUMN id RESTART WITH 1;
ALTER TABLE member ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;
